In [1]:
import pandas as pd 
import numpy as np 
import re

In [2]:
df = pd.read_csv('data_sources/OxCGRT_latest.csv',dtype=object)

In [3]:
# Change date format
df['Date'] = pd.to_datetime(df['Date'])
df.head()

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,NAT_TOTAL,2020-01-01,0.00,NaN,0.00,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,Aruba,ABW,NaN,NaN,NAT_TOTAL,2020-01-02,0.00,NaN,0.00,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,Aruba,ABW,NaN,NaN,NAT_TOTAL,2020-01-03,0.00,NaN,0.00,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,Aruba,ABW,NaN,NaN,NAT_TOTAL,2020-01-04,0.00,NaN,0.00,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,Aruba,ABW,NaN,NaN,NAT_TOTAL,2020-01-05,0.00,NaN,0.00,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [4]:
# Filter out for Canada measures only
df = df[(df.CountryName == 'Canada') & (df.RegionName == 'Ontario')]

In [5]:
# Drop non_used columns 
cols = ['CountryName', 'RegionName', 'Jurisdiction', 'Date']
pattern = re.compile('C[0-9]_*')
for c in df.columns:
    if (pattern.match(c) and not c.endswith('Flag')) or (c.startswith('H6') and not c.endswith('Flag')) or c.startswith('H3'):
        cols.append(c)

df = df[cols]

In [6]:
df.dtypes

CountryName                                     object
RegionName                                      object
Jurisdiction                                    object
Date                                    datetime64[ns]
C1_School closing                               object
C2_Workplace closing                            object
C3_Cancel public events                         object
C4_Restrictions on gatherings                   object
C5_Close public transport                       object
C6_Stay at home requirements                    object
C7_Restrictions on internal movement            object
C8_International travel controls                object
H3_Contact tracing                              object
H6_Facial Coverings                             object
dtype: object

In [7]:
print(df.columns)

Index(['CountryName', 'RegionName', 'Jurisdiction', 'Date',
       'C1_School closing', 'C2_Workplace closing', 'C3_Cancel public events',
       'C4_Restrictions on gatherings', 'C5_Close public transport',
       'C6_Stay at home requirements', 'C7_Restrictions on internal movement',
       'C8_International travel controls', 'H3_Contact tracing',
       'H6_Facial Coverings'],
      dtype='object')

In [8]:
df.columns = ['country', 'province','jurisdiction','date', 'school_closure', 
              'workplace_closure','cancel_public_event',
              'restrictions_on_gatherings', 'close_public_transport','stay_at_home','restrictions_internal_mvt',
              'intern_travel_control', 'contact_tracing', 'facial_coverings']

In [9]:
df.head()

,country,province,jurisdiction,date,school_closure,workplace_closure,cancel_public_event,restrictions_on_gatherings,close_public_transport,stay_at_home,restrictions_internal_mvt,intern_travel_control,contact_tracing,facial_coverings
26560,Canada,Ontario,STATE_TOTAL,2020-01-01,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
26561,Canada,Ontario,STATE_TOTAL,2020-01-02,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
26562,Canada,Ontario,STATE_TOTAL,2020-01-03,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
26563,Canada,Ontario,STATE_TOTAL,2020-01-04,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
26564,Canada,Ontario,STATE_TOTAL,2020-01-05,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

Select rows between October 6th and February 6th

In [10]:
# Select only rows between October 6th and February 6th
df = df[(df.date > '2020-10-05') & (df.date <= '2021-02-06')]

In [11]:
df.head()

,country,province,jurisdiction,date,school_closure,workplace_closure,cancel_public_event,restrictions_on_gatherings,close_public_transport,stay_at_home,restrictions_internal_mvt,intern_travel_control,contact_tracing,facial_coverings
26839,Canada,Ontario,STATE_TOTAL,2020-10-06,2.00,2.00,1.00,3.00,1.00,0.00,0.00,4.00,1.00,2.00
26840,Canada,Ontario,STATE_TOTAL,2020-10-07,2.00,2.00,1.00,3.00,1.00,0.00,0.00,4.00,1.00,2.00
26841,Canada,Ontario,STATE_TOTAL,2020-10-08,2.00,2.00,1.00,3.00,1.00,0.00,0.00,4.00,1.00,2.00
26842,Canada,Ontario,STATE_TOTAL,2020-10-09,2.00,2.00,1.00,3.00,1.00,0.00,0.00,4.00,1.00,2.00
26843,Canada,Ontario,STATE_TOTAL,2020-10-10,2.00,2.00,1.00,4.00,1.00,1.00,0.00,4.00,1.00,2.00

In [12]:
df.tail()

,country,province,jurisdiction,date,school_closure,workplace_closure,cancel_public_event,restrictions_on_gatherings,close_public_transport,stay_at_home,restrictions_internal_mvt,intern_travel_control,contact_tracing,facial_coverings
26958,Canada,Ontario,STATE_TOTAL,2021-02-02,3.00,3.00,2.00,4.00,1.00,2.00,1.00,4.00,1.00,2.00
26959,Canada,Ontario,STATE_TOTAL,2021-02-03,3.00,3.00,2.00,4.00,1.00,2.00,1.00,4.00,1.00,2.00
26960,Canada,Ontario,STATE_TOTAL,2021-02-04,3.00,3.00,2.00,4.00,1.00,2.00,1.00,4.00,1.00,2.00
26961,Canada,Ontario,STATE_TOTAL,2021-02-05,3.00,3.00,2.00,4.00,1.00,2.00,1.00,4.00,1.00,2.00
26962,Canada,Ontario,STATE_TOTAL,2021-02-06,3.00,3.00,2.00,4.00,1.00,2.00,1.00,4.00,1.00,2.00

Delete empty rows

In [13]:
df = df.dropna()

Convert measures to floats

In [14]:
for c in df.columns:
    if c == 'country' or c == 'province' or c == 'jurisdiction' or c == 'date':
        continue
    df[c] = pd.to_numeric(df[c])

In [15]:
df.dtypes

country                               object
province                              object
jurisdiction                          object
date                          datetime64[ns]
school_closure                       float64
workplace_closure                    float64
cancel_public_event                  float64
restrictions_on_gatherings           float64
close_public_transport               float64
stay_at_home                         float64
restrictions_internal_mvt            float64
intern_travel_control                float64
contact_tracing                      float64
facial_coverings                     float64
dtype: object

Plan 1:
1. Remove economic/health/misc policy columns
2. Each column represents a measure: can use number combination to identify all the measures taking place on a specific date 
3. Remove blanks 
4. Add keyword 1
5. Fill in remaining days from Jan31st to Feb6th

Plan 2:
1. From this info create table where row = restriction
2. Infer start and end dates 
3. Infer keywords and descriptions 

https://github.com/OxCGRT/covid-policy-tracker/blob/master/documentation/codebook.md#containment-and-closure-policies

In [16]:
#Create special measures dimension
special_measures_dimension = pd.DataFrame(columns=['Title', 'value', 'Description', 'keyword_1', 'keyword_2', 'start_date', 'end_date'])

In [17]:
for c in df.columns:
    if c == 'country' or c == 'province' or c == 'jurisdiction' or c == 'date':
        continue
    # Group rows by consecutive same values of the specific row
    df_groups = df.groupby((df[c].shift() != df[c]).cumsum())
    
    for name, group in df_groups:
        # Access each group 
        gdf = df_groups.get_group(name)
        gsize = len(gdf)
        start_date = None
        end_date = None
        value = None
        title = description = c 
        keyword_1 = c.split('_')[0] 
        keyword_2 = c.split('_')[1:]
        keyword_2 = '-'.join(keyword_2)
        i = 0
        for i, (idx, row) in enumerate(gdf.iterrows()):
            if i == 0: #record start date
                start_date = row['date']
            if i == (gsize-1): #record end date 
                end_date = row['date']
            if not value: #record the value (will need to drop 0s later)
                value = row[c]
        special_measure_row = [title, value, description, keyword_1, keyword_2, start_date, end_date]
        special_measures_dimension.loc[len(special_measures_dimension)] = special_measure_row

In [18]:
special_measures_dimension.head()

,Title,value,Description,keyword_1,keyword_2,start_date,end_date
0,school_closure,2.0,school_closure,school,closure,2020-10-06,2020-10-22
1,school_closure,1.0,school_closure,school,closure,2020-10-23,2020-10-29
2,school_closure,2.0,school_closure,school,closure,2020-10-30,2020-12-18
3,school_closure,3.0,school_closure,school,closure,2020-12-19,2021-02-06
4,workplace_closure,2.0,workplace_closure,workplace,closure,2020-10-06,2020-11-22

In [19]:
# Remove rows for which value is 0 
special_measures_dimension = special_measures_dimension[special_measures_dimension.value != 0]

In [20]:
special_measures_dimension.head()

,Title,value,Description,keyword_1,keyword_2,start_date,end_date
0,school_closure,2.0,school_closure,school,closure,2020-10-06,2020-10-22
1,school_closure,1.0,school_closure,school,closure,2020-10-23,2020-10-29
2,school_closure,2.0,school_closure,school,closure,2020-10-30,2020-12-18
3,school_closure,3.0,school_closure,school,closure,2020-12-19,2021-02-06
4,workplace_closure,2.0,workplace_closure,workplace,closure,2020-10-06,2020-11-22

In [21]:
special_measures_dimension.tail()

,Title,value,Description,keyword_1,keyword_2,start_date,end_date
16,intern_travel_control,4.0,intern_travel_control,intern,travel-control,2020-10-06,2021-02-06
17,contact_tracing,1.0,contact_tracing,contact,tracing,2020-10-06,2020-11-03
18,contact_tracing,2.0,contact_tracing,contact,tracing,2020-11-04,2020-11-18
19,contact_tracing,1.0,contact_tracing,contact,tracing,2020-11-19,2021-02-06
20,facial_coverings,2.0,facial_coverings,facial,coverings,2020-10-06,2021-02-06

Map the values to descriptions

In [22]:
# Replace value by description 
school_closure = {
    1:'recommend closing or all schools open with alterations',
    2: ' require closing (only some levels or categories, eg just high school, or just public schools)',
    3:'require closing all levels'
                 }

workplace_closure = {
    1:'recommend closing (or recommend work from home)',
    2:'require closing (or work from home) for some sectors or categories of workers',
    3:'require closing (or work from home) for all-but-essential workplaces (eg grocery stores, doctors)'
}

cancel_public_event = {
    1:'recommend cancelling',
    2:'require cancelling'
}

restrictions_on_gatherings = {
    1:'restrictions on very large gatherings (the limit is above 1000 people)',
    2:'restrictions on gatherings between 101-1000 people',
    3:'restrictions on gatherings between 11-100 people',
    4:'restrictions on gatherings of 10 people or less'
    
}

close_public_transport = {
    1:'recommend closing (or significantly reduce volume/route/means of transport available)',
    2:'require closing (or prohibit most citizens from using it)'
}

stay_at_home = {
    1:'recommend not leaving house',
    2:'require not leaving house with exceptions for daily exercise, grocery shopping, and \'essential\' trips',
    3:'require not leaving house with minimal exceptions (eg allowed to leave once a week, or only one person can leave at a time, etc)'
}

restrictions_internal_mvt = {
    1:'recommend not to travel between regions/cities',
    2:'internal movement restrictions in place'
}

intern_travel_control = {
    1:'screening arrivals',
    2:'quarantine arrivals from some or all regions',
    3:'ban arrivals from some regions',
    4:'ban on all regions or total border closure'
}

contact_tracing = {
    1:'limited contact tracing; not done for all cases',
    2:'comprehensive contact tracing; done for all identified cases'
}

facial_coverings = {
    1:'recommended facial coverings',
    2:'facial covering required in some specified shared/public spaces outside the home with other people present, or some situations when social distancing not possible',
    3:'facial covering required in all shared/public spaces outside the home with other people present or all situations when social distancing not possible',
    4:'facial covering required outside the home at all times regardless of location or presence of other people'
    
}

In [23]:
special_measures_df = pd.DataFrame(columns=['Title', 'Description', 'keyword_1', 'keyword_2', 'start_date', 'end_date', 'value'])

In [24]:
# Map each value to the description and add description to the new df 
for idx, row in special_measures_dimension.iterrows():
    m_row = [row['Title']]
    descr = globals()[row['Title']][int(row['value'])]
    m_row.append(descr)
    m_row.append(row['keyword_1'])
    m_row.append(row['keyword_2'])
    m_row.append(row['start_date'])
    m_row.append(row['end_date'])
    m_row.append(row['value'])
    special_measures_df.loc[len(special_measures_df)] = m_row

In [25]:
special_measures_df.head()

,Title,Description,keyword_1,keyword_2,start_date,end_date,value
0,school_closure,require closing (only some levels or categori...,school,closure,2020-10-06,2020-10-22,2.0
1,school_closure,recommend closing or all schools open with alt...,school,closure,2020-10-23,2020-10-29,1.0
2,school_closure,require closing (only some levels or categori...,school,closure,2020-10-30,2020-12-18,2.0
3,school_closure,require closing all levels,school,closure,2020-12-19,2021-02-06,3.0
4,workplace_closure,require closing (or work from home) for some s...,workplace,closure,2020-10-06,2020-11-22,2.0

Add surrogate keys

In [26]:
special_measures_df.insert(0, "Special_Measures_key",  np.arange(len(special_measures_df)))

In [27]:
special_measures_df.head()

,Special_Measures_key,Title,Description,keyword_1,keyword_2,start_date,end_date,value
0,0,school_closure,require closing (only some levels or categori...,school,closure,2020-10-06,2020-10-22,2.0
1,1,school_closure,recommend closing or all schools open with alt...,school,closure,2020-10-23,2020-10-29,1.0
2,2,school_closure,require closing (only some levels or categori...,school,closure,2020-10-30,2020-12-18,2.0
3,3,school_closure,require closing all levels,school,closure,2020-12-19,2021-02-06,3.0
4,4,workplace_closure,require closing (or work from home) for some s...,workplace,closure,2020-10-06,2020-11-22,2.0

Export clean dimension to CSV

In [28]:
special_measures_df.to_csv("dimensions/special_measures_dimension.csv",index=False)